config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: :registrations }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member  do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: %i[index]

  namespace :admin do
    root 'tests#index'

    resources :badges do
      resource :badge_rule, as: :rule, except: :show
    end

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: %i[show index]
      end
    end

    resources :gists, only: %i[index]
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users
  has_one :rule, class_name: 'BadgeRule', dependent: :destroy

  validates :caption, presence: true
  validates :image, presence: true

  def self.images
    Dir.glob('app/assets/images/badges/*').map { |image| [File.basename(image), image.gsub('app/assets/images/', '')] }
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[edit update destroy show]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path 
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:caption, :image)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = Badge.all
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.caption %></td>
  <td><%= image_tag badge.image %></td>
  <td>
    <%= render 'badge_rule', badge: badge %>
  </td>
  <td>
    <div class='btn-group' role='group'>
      <%= link_to t('.show'), admin_badge_path(badge), class: 'btn btn-primary' %>
      <%= link_to t('.edit'), edit_admin_badge_path(badge), class: 'btn btn-secondary' %>
      <%= link_to t('.destroy'), admin_badge_path(badge), method: :delete, data: { confirm: t('dialogs.are_you_sure')}, class: 'btn btn-danger'  %>
    </div>
  </td>
</tr>

app/views/admin/badges/_badge_rule.erb
<% if badge.rule %>
  <dl class='row'>
    <dt class='col-lg-3'><%= BadgeRule.human_attribute_name(:rule_type) %> </dt>
    <dd class='col-lg-9'><%= t(badge.rule.rule_type, scope: [:badge_rule, :type]) %></dd>

    <dt class='col-lg-3'><%= BadgeRule.human_attribute_name(:unique) %></dt>
    <dd class='col-lg-9'><%= badge.rule.unique ? octicon('check') : octicon('x') %></dd>
    
    <% if badge.rule.options.params.include? :first_try %>
      <dt class='col-lg-3'><%= BadgeRule.human_attribute_name(:first_try) %></dt>
      <dd class='col-lg-9'><%= badge.rule.unique ? octicon('check') : octicon('x') %></dd>    
    <% end %>

    <% if badge.rule.options.params.include? :level %>
      <dt class='col-lg-3'><%= BadgeRule.human_attribute_name(:level) %></dt>
      <dd class='col-lg-9'><%= badge.rule.level %></dd>    
    <% end %>

    <dt class='col-lg-3'><%= BadgeRule.human_attribute_name(:resource) %></dt>
    <dd class='col-lg-9'><%= badge.rule.resource ? "#{badge.rule.resource.title}" : t('.any') %></dd>
  </dl>
  <div class='btn-group' role='group'>
    <button class='btn btn-primary dropdown-toggle btn-primary m-3' type='button' id='dropdownRuleButton' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
      <%= t('.action') %>
    </button>
    <div class='dropdown-menu' aria-labelledby='dropdownRuleButton'>
      <%= link_to t('.edit'), edit_admin_badge_rule_path(badge), class: 'dropdown-item' %>
      <%= link_to t('.destroy'), admin_badge_rule_path(badge), method: :delete, data: { confirm: t('dialogs.are_you_sure')}, class: 'dropdown-item'  %>
    </div>
  </div>
<% else %>
  <div class='btn-group' role='group'>
    <div class='btn-group' role='group'>
      <button class='btn btn-primary dropdown-toggle btn-primary m-3' type='button' id='dropdownRuleButton' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
        <%= t('.create') %>
      </button>
      <div class='dropdown-menu' aria-labelledby='dropdownRuleButton'>
        <%= link_to t('.test_rule'), new_admin_badge_rule_path(badge, badge_rule: { rule_type: 'test' } ), class: 'dropdown-item' %>
        <%= link_to t('.category_rule'), new_admin_badge_rule_path(badge, badge_rule: { rule_type: 'category'} ), class: 'dropdown-item' %>
        <%= link_to t('.level_rule'), new_admin_badge_rule_path(badge, badge_rule: { rule_type: 'level' } ), class: 'dropdown-item' %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/badges/_badge_rule.html.erb
<% if badge.rule %>
  <dl class='row'>
    <dt class='col-lg-3'><%= BadgeRule.human_attribute_name(:rule_type) %> </dt>
    <dd class='col-lg-9'><%= t(badge.rule.rule_type, scope: [:badge_rule, :type]) %></dd>

    <dt class='col-lg-3'><%= BadgeRule.human_attribute_name(:unique) %></dt>
    <dd class='col-lg-9'><%= badge.rule.unique ? octicon('check') : octicon('x') %></dd>
    
    <% if badge.rule.params.include? :first_try %>
      <dt class='col-lg-3'><%= BadgeRule.human_attribute_name(:first_try) %></dt>
      <dd class='col-lg-9'><%= badge.rule.first_try ? octicon('check') : octicon('x') %></dd>    
    <% end %>

    <% if badge.rule.params.include? :level %>
      <dt class='col-lg-3'><%= BadgeRule.human_attribute_name(:level) %></dt>
      <dd class='col-lg-9'><%= badge.rule.level %></dd>    
    <% end %>
    
    <% if badge.rule.params.include? :category %>
      <dt class='col-lg-3'><%= BadgeRule.human_attribute_name(:category) %></dt>
      <dd class='col-lg-9'><%= badge.rule.category ? "#{badge.rule.category.title}" : t('.any') %></dd>
    <% end %>

    <% if badge.rule.params.include? :test %>
      <dt class='col-lg-3'><%= BadgeRule.human_attribute_name(:test) %></dt>
      <dd class='col-lg-9'><%= badge.rule.test ? "#{badge.rule.test.title}" : t('.any') %></dd>
    <% end %>
  </dl>
  <div class='btn-group' role='group'>
    <button class='btn btn-primary dropdown-toggle btn-primary m-3' type='button' id='dropdownRuleButton' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
      <%= t('.actions') %>
    </button>
    <div class='dropdown-menu' aria-labelledby='dropdownRuleButton'>
      <%= link_to t('.edit'), edit_admin_badge_rule_path(badge), class: 'dropdown-item' %>
      <%= link_to t('.destroy'), admin_badge_rule_path(badge), method: :delete, data: { confirm: t('dialogs.are_you_sure')}, class: 'dropdown-item'  %>
    </div>
  </div>
<% else %>
  <div class='btn-group' role='group'>
    <div class='btn-group' role='group'>
      <button class='btn btn-primary dropdown-toggle btn-primary m-3' type='button' id='dropdownRuleButton' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
        <%= t('.create') %>
      </button>
      <div class='dropdown-menu' aria-labelledby='dropdownRuleButton'>
        <%= link_to t('test', scope: [:badge_rule, :type]), new_admin_badge_rule_path(badge, badge_rule: { rule_type: 'test' } ), class: 'dropdown-item' %>
        <%= link_to t('category', scope: [:badge_rule, :type]), new_admin_badge_rule_path(badge, badge_rule: { rule_type: 'category'} ), class: 'dropdown-item' %>
        <%= link_to t('level', scope: [:badge_rule, :type]), new_admin_badge_rule_path(badge, badge_rule: { rule_type: 'level' } ), class: 'dropdown-item' %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/badges/_form.html.erb
<%= form_with(model: [:admin, @badge], local: true) do |form| %>
  <%= render 'shared/validation_errors', resource: @badge %>
  <div class='form-group'>
    <%= form.label :caption %>
    <%= form.text_field :caption, id: :badge_caption, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= form.label :image %>
    <%= form.select :image, Badge.images, {}, { class: 'form-control custom-select custom-select-lg' } %>
  </div>
  <%= form.submit class: 'btn btn-primary btn-block' %>
<% end %>

app/views/admin/badges/edit.html.erb
<div class='card col-lg-8 offset-lg-2 border rounded my-3 text-xs-center'>
  <div class='card-body'>
    <%= render 'form' %>
    <div class='btn-group my-3 btn-block' role='group'>
      <%= link_to t('.badges'), admin_badges_path, class: 'btn btn-secondary' %>
      <%= link_to t('.show'), admin_badge_path(@badge), class: 'btn btn-secondary' %>
      <%= link_to t('.destroy'), admin_badge_path(@badge), method: :delete, data: { confirm: t('dialogs.are_you_sure')}, class: 'btn btn-danger'  %>
    </div>
  </div>
</div>

app/views/admin/badges/index.html.erb
<div class="table-responsive">
  <table class='table table-striped'>
    <thead>
      <tr>
        <th class=''><%= Badge.human_attribute_name(:caption) %></th>
        <th class=''><%= Badge.human_attribute_name(:image) %></th>
        <th class='col-lg-6'><%= Badge.human_attribute_name(:rule) %></th>
        <th class=''><%= t('.actions') %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @badges %>
    </tbody>
  </table>
</div>
<%= link_to t('.create'), new_admin_badge_path, class: 'btn btn-primary' %>

app/views/admin/badges/show.html.erb
<div class='card col-lg-8 offset-lg-2'>
  <div class="card-body">
    <h3 class='card-title'><%= @badge.caption %></h3>
    <%= image_tag @badge.image %>
    <div class='btn-group my-5' role='group'>
      <%= link_to t('.badges'), admin_badges_path, class: 'btn btn-primary' %>
      <%= link_to t('.edit'), edit_admin_badge_path(@badge), class: 'btn btn-secondary' %>
      <%= link_to t('.destroy'), admin_badges_path(@badge), method: :delete, data: { confirm: t('dialogs.are_you_sure')}, class: 'btn btn-danger'  %>
    </div>
  </div>
</div>