config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: :registrations }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member  do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: %i[index]

  namespace :admin do
    root 'tests#index'

    resources :badges do
      resource :badge_rule, as: :rule, except: :show
    end

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: %i[show index]
      end
    end

    resources :gists, only: %i[index]
  end
end

app/views/admin/_navigation.html.erb
<nav class='navbar navbar-dark bg-dark navbar-expand-lg'>
  <%= link_to t('title'), root_path, class: 'navbar-brand h1' %>
  <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
    <span class='navbar-toggler-icon'></span>
  </button>
  <div class='collapse navbar-collapse' id='navbarSupportedContent'>
    <% if user_signed_in? %>
      <span class='navbar-text'>
        <%= t('welcome_admin_html', email: current_user.email) %>
      </span>
    <% end %>
    <ul class='navbar-nav ml-auto'>
      <li class='nav-item'>
        <%= link_to t('.tests'), admin_tests_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to t('.create_test'), new_admin_test_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to t('.gists'), admin_gists_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to t('.badges'), admin_badges_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>