config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: :registrations }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member  do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: %i[index]

  namespace :admin do
    root 'tests#index'

    resources :badges do
      resource :badge_rule, as: :rule, except: :show
    end

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: %i[show index]
      end
    end

    resources :gists, only: %i[index]
  end
end

app/views/shared/_flash.html.erb
<div class='m-3'>
  <% flash.each do |key, message| %>
    <%= flash_message(message, key) %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class='text-center card'>
  <div class='card-body'>
    <div>
      <%= current_year %>
      <%= github_url(TestGuru::AUTHOR, TestGuru::PROJECT_GIT_URL) %>
    </div>
    <div>
      <%= t('.description') %>
      <%= link_to('Thinknetica', 'http://www.thinknetica.com', target: '_blank') %>
    </div>
  </div>
</footer>

app/views/shared/_locales.html.erb
<li class='nav-item dropdown'>
  <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
    <%= t('.language')%>
  </a>
  <div class='dropdown-menu' aria-labelledby='navbarDropdown'>
    <%= link_to_unless I18n.locale == :ru, 'RU', '?locale=ru' %> 
    <div class='dropdown-divider'></div>
    <%= link_to_unless I18n.locale == :en, 'EN', '?locale=en' %>
  </div>
</li>

app/views/shared/_navigation.html.erb
<nav class='navbar navbar-light bg-light navbar-expand-lg border-bottom border-primary'>
  <%= link_to t('title'), root_path, class: 'navbar-brand h1' %>
  <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
    <span class='navbar-toggler-icon'></span>
  </button>
  <div class='collapse navbar-collapse' id='navbarSupportedContent'>
    <% if user_signed_in? %>
      <span class='navbar-text'>
        <%= t('welcome_user_html', email: current_user.email) %>
      </span>
    <% end %>
    <ul class='navbar-nav ml-auto'>
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <li class='nav-item'>
            <%= link_to t('.admin_panel'), admin_tests_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class='nav-item dropdown'>
          <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
            <%= t('.sort') %>
          </a>
          <div class='dropdown-menu' aria-labelledby='navbarDropdown'>
            <div class='dropdown-item pointer tests-order' id='sort-by-title'>
              <%= t('.by_title') %>
              <%= octicon 'arrow-up', class: 'text-success hide' %>
              <%= octicon 'arrow-down', class: 'text-success hide' %>
            </div>
            <div class='dropdown-item pointer tests-order' id='sort-by-category'>
              <%= t('.by_category') %>
              <%= octicon 'arrow-up', class: 'text-success hide' %>
              <%= octicon 'arrow-down', class: 'text-success hide' %>
            </div>
            <div class='dropdown-item pointer tests-order' id='sort-by-level'>
              <%= t('.by_level') %>
              <%= octicon 'arrow-up', class: 'text-success hide' %>
              <%= octicon 'arrow-down', class: 'text-success hide' %>
            </div>
          </div>
        </li>
        <li class='nav-item'>
          <%= link_to t('.feedback'), new_feedback_path, class: 'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to t('.badges'), badges_path, class: 'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to t('.edit_user'),  edit_user_registration_path, class: 'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to t('.logout'), destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class='nav-item'>
          <%= link_to t('.login'), new_user_session_path, class: 'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to t('.signup'), new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
      <%= render 'shared/locales' %>
    </ul>
  </div>
</nav>

app/views/shared/_validation_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, id: 'error_explanation', class: 'resource-errors card text-white bg-danger m-3', data: { resource_id: resource.id } do %>
    <div class='card-header'>
      <%= t('.error', count: resource.errors.count) %>
    </div>
    <ul class='list-group list-group-flush text-danger'>
      <% resource.errors.full_messages.each do |message| %>
        <li class='list-group-item'><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>