config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: :registrations }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member  do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: %i[index]

  namespace :admin do
    root 'tests#index'

    resources :badges do
      resource :badge_rule, as: :rule, except: :show
    end

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: %i[show index]
      end
    end

    resources :gists, only: %i[index]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  MAXIMUM_ANSWES = 4

  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_count

  private

  def validate_count
    maximum = question && question.answers.size > MAXIMUM_ANSWES
    errors.add(:count, I18n.t('.too_much', count: MAXIMUM_ANSWES)) if maximum
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_answer, only: %i[edit update destroy]
  before_action :find_question, only: %i[new create]

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to [:admin, @answer.question]
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to [:admin, @answer.question]
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to [:admin, @answer.question]
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/views/admin/answers/_answer.html.erb
<tr>
  <td><%= answer.body %></td>
  <td><%= answer.correct ? octicon('check') : octicon('x') %></td>
  <td>
    <div class='btn-group' role='group'>
      <%= link_to t('.edit'), edit_admin_answer_path(answer), class: 'btn btn-secondary' %>
      <%= link_to t('.destroy'), admin_answer_path(answer), method: :delete, data: { confirm: t('dialogs.are_you_sure')}, class: 'btn btn-danger' %>
    </div>
  </td>
<tr>

app/views/admin/answers/_form.html.erb
<%= form_with(model: [:admin, @question, @answer], local: true) do |form| %>
  <%= render 'shared/validation_errors', resource: @answer %>
  <div class='form-group'>
    <%= form.label :body %>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60, class: 'form-control' %>
  </div>
  <div class='custom-control custom-checkbox m-3'>
    <%= form.check_box :correct, id: :answer_correct, class: 'custom-control-input' %>
    <%= form.label :correct, class: 'custom-control-label' %>
  </div>
  <%= form.submit class: 'btn btn-primary btn-block' %>
<% end %>

app/views/admin/answers/edit.html.erb
<div class='card col-lg-8 offset-lg-2 border rounded my-3 text-xs-center'>
  <div class='card-body'>
    <h1 class='card-title'><%= t('.edit_answer')%></h1>
    <p>
      <%= @answer.question.body %>
    </p>
    <%= render 'form' %>
    <div class='btn-group my-3 btn-block' role='group'>
      <%= link_to t('.question'), admin_question_path(@answer.question), class: 'btn btn-secondary' %>
      <%= link_to t('.destroy'), admin_answer_path(@answer), method: :delete, data: { confirm: t('dialogs.are_you_sure')}, class: 'btn btn-secondary'  %>
    </div>
  </div>
</div>

app/views/admin/answers/new.html.erb
<div class='card col-lg-8 offset-lg-2 border rounded my-3 text-xs-center'>
  <div class='card-body'>
    <h1 class='card-title'><%= t('.new_answer')%></h1>
    <p>
      <%= @question.body %>
    </p>
    <%= render 'form' %>
    <%= link_to t('.question'), admin_question_path(@question), class: 'btn btn-secondary my-3 btn-block' %>
  </div>
</div>